
[buildPlans.afio]
family = "afio"
spacing = "term"
serifs = "sans"
noCvSs = true
exportGlyphNames = true

  [buildPlans.afio.variants]
  inherits = "ss14"


[buildPlans.afio.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

# [buildPlans.afio.slopes.oblique]
# angle = 9.4
# shape = "oblique"
# menu = "oblique"
# css = "oblique"

###################################################################################################
# Override default building weights
# When buildPlans.<plan name>.weights is absent, all weights would built and mapped to
# default values.
# IMPORTANT : Currently "menu" and "css" property only support numbers between 0 and 1000.
#             and "shape" properly only supports number between 100 and 900 (inclusive).
#             If you decide to use custom weights you have to define all the weights you
#             plan to use otherwise they will not be built.
[buildPlans.afio.weights.Thin]
shape = 100
menu = 100
css = 100

[buildPlans.afio.weights.ExtraLight]
shape = 200
menu = 200
css = 200

[buildPlans.IosevkaCustom.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.afio.weights.regular]
shape = 300
menu  = 400
css   = 400

[buildPlans.afio.weights.medium]
shape = 400
menu  = 500
css   = 500

[buildPlans.afio.weights.bold]
shape = 500
menu  = 700
css   = 700

# End weight section
###################################################################################################

###################################################################################################
# Override default building slant sets
# Format: <upright|italic|oblique> = <"normal"|"italic"|"oblique">
# When this section is absent, all slants would be built.

[buildPlans.afio.slants]
upright = "normal"
# italic = "italic"
# oblique = "oblique"

# End slant section
###################################################################################################

###################################################################################################
# Override default building widths
# When buildPlans.<plan name>.widths is absent, all widths would built and mapped to
# default values.
# IMPORTANT : Currently "shape" property only supports integers between 3 and 9 (inclusive), while
#             "menu" only supports integers between 1 and 9 (inclusive).
#             If you decide to use custom widths you have to define all the widths you
#             plan to use otherwise they will not be built.

[buildPlans.afio.widths.Normal]
shape = 500
menu = 5
css = "normal"

[buildPlans.afio.widths.Condensed]
shape = 416
menu = 3
css = "condensed"

[buildPlans.afio.widths.SemiCondensed]
shape = 456
menu = 4
css = "semi-condensed"

###################################################################################################
# Metric overrides
# Certain metrics like line height (leading) could be overridden in your build plan file.
# Edit the values to change the metrics. Remove this section when overriding is not needed.

# [buildPlans.afio.metric-override]
# leading = 1250
# winMetricAscenderPad = 0
# winMetricDescenderPad = 0
# powerlineScaleY = 1
# powerlineScaleX = 1
# powerlineShiftY = 0
# powerlineShiftX = 0

# End metric override section
###################################################################################################
